config/routes.rb
Rails.application.routes.draw do
  authenticate :user do
    mount Avo::Engine, at: Avo.configuration.root_path
  end

  # Mock Azure Active Directory Authentication
  #
  # These routes serve two purposes.
  # 1. The named routes provide easy usage for real production views where we
  #    need to login with Azure. These are the Azure auth routes.
  # 2. When the mock is enabled, we resolve the routes to a mock controller.
  #    When the middleware MockAzureAuthMiddleware is inserted to intercept the
  #    cookie, the Azure::MockSessions controller behaves like real Azure Auth.
  #
  # These routes will never make it to the controller in production.
  # Azure will intercept the routes before they ever get to the app.

  # The constraints help prevent access when running elsewhere, e.g. Heroku.
  constraints(-> { Rails.application.config.azure_auth_mocked }) do
    scope path: "users/auth/azure", as: "azure", module: "azure" do
      post "login", to: "mock_sessions#create"
      get "logout", to: "mock_sessions#destroy", as: :logout
    end
  end

  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
  }
  get "/users/password", to: redirect("/users/password/new")

  get "/get-started", to: "start#index"
  resources :start, path: "get-started", only: %i[index create show update]
  resources :plans, only: %i[show index create update destroy]
  resources :worksheets, only: %i[show]
  resources :costsheets, only: %i[show]
  resources :reference_library_documents, only: %i[] do
    get :download
  end
  get "plan/goals/:country_name/:assessment_type(/:plan_term)",
    to: "plans#goals", as: "plan_goals"

  ##
  # static pages
  get "/assess", to: "pages#assess"
  get "/develop", to: "pages#develop"
  get "/implement", to: "pages#implement"
  get "/privacy_policy", to: "pages#privacy_policy"
  get "/reference-library",
      to: "pages#reference_library", as: "reference_library" # Benchmark Document section
  get "/document/introduction", to: "pages#introduction", as: "introduction"
  get "/document/1-national-legislation-policy-and-financing",
      to: "pages#technical_area_1", as: "technical_area_1"
  get "/document/2-ihr-coordination-communication-and-advocacy-and-reporting",
      to: "pages#technical_area_2", as: "technical_area_2"
  get "/document/3-antimicrobial-resistance",
      to: "pages#technical_area_3", as: "technical_area_3"
  get "/document/4-zoonotic-disease",
      to: "pages#technical_area_4", as: "technical_area_4"
  get "/document/5-food-safety",
      to: "pages#technical_area_5", as: "technical_area_5"
  get "/document/6-immunization",
      to: "pages#technical_area_6", as: "technical_area_6"
  get "/document/7-national-laboratory-system",
      to: "pages#technical_area_7", as: "technical_area_7"
  get "/document/8-biosafety-and-biosecurity",
      to: "pages#technical_area_8", as: "technical_area_8"
  get "/document/9-surveillance",
      to: "pages#technical_area_9", as: "technical_area_9"
  get "/document/10-human-resources",
      to: "pages#technical_area_10", as: "technical_area_10"
  get "/document/11-emergency-preparedness",
      to: "pages#technical_area_11", as: "technical_area_11"
  get "/document/12-emergency-response-operations",
      to: "pages#technical_area_12", as: "technical_area_12"
  get "/document/13-linking-public-health-and-security-authorities",
      to: "pages#technical_area_13", as: "technical_area_13"
  get "/document/14-medical-countermeasures-and-personnel-deployment",
      to: "pages#technical_area_14", as: "technical_area_14"
  get "/document/15-risk-communication",
      to: "pages#technical_area_15", as: "technical_area_15"
  get "/document/16-points-of-entry",
      to: "pages#technical_area_16", as: "technical_area_16"
  get "/document/17-chemical-events",
      to: "pages#technical_area_17", as: "technical_area_17"
  get "/document/18-radiation-emergencies",
      to: "pages#technical_area_18", as: "technical_area_18"
  get "/document/acronyms", to: "pages#acronyms", as: "acronyms"
  get "/document/glossary", to: "pages#glossary", as: "glossary"
  get "/document/acknowledgement",
      to: "pages#acknowledgement", as: "acknowledgement"

  get "/healthcheck", to: "healthchecks#index", as: "healthcheck"

  root to: "pages#home"
end

app/controllers/start_controller.rb
class StartController < ApplicationController
  before_action :require_country_id, only: %i[create show update]
  before_action :set_get_started_form

  def index
    @countries = Country.all_assessed
  end

  def create
    if @get_started_form.blank_assessment
      redirect_to start_url(id: @get_started_form.country_id, blank: true)
    else
      redirect_to start_url(id: @get_started_form.country_id)
    end
  end

  def show
    @country = @get_started_form.country
    @publications = @country.publications_for_selection
    @diseases = Disease.all.order(:created_at)
  end

  def update
    return show && render(:show) unless @get_started_form.valid?

    redirect_to plan_goals_url(
                  country_name: @get_started_form.country.name,
                  assessment_type: @get_started_form.assessment_type,
                  plan_term: @get_started_form.plan_term_s,
                  areas:
                    if @get_started_form.technical_area_ids.present?
                      @get_started_form.technical_area_ids.join("-")
                    else
                      nil
                    end,
                  diseases:
                    if @get_started_form.diseases.present?
                      @get_started_form.diseases.join("-")
                    else
                      nil
                    end
                )
  end

  private

  def set_get_started_form
    form_params = params.fetch(:get_started_form, {}).permit!.to_h
    form_params[:country_id] = @country_id if @country_id
    form_params[:blank_assessment] = params[:blank] if params.key?(:blank)
    @get_started_form = GetStartedForm.new(form_params)
  end

  def require_country_id
    @country_id = params[:id] || params.dig(:get_started_form, :country_id)

    if @country_id.blank?
      flash[:alert] = "Choose a country to get started"
      return redirect_to(start_index_path)
    end
  end
end

app/views/start/_checkbox_for_technical_area.html.haml
.text-nowrap
  = check_box_tag "get_started_form[technical_area_ids][]", technical_area.id, false, {class: "form-check-inline", id: "technical_area_id_#{technical_area.id}", "data-get-started-target": "checkboxForTechnicalArea", autocomplete: "off"}
  %label{for: "technical_area_id_#{technical_area.id}"}= technical_area.text

app/views/start/index.html.haml
.row{id: "get_started", "data-controller": "get-started"}
  .col
    %h1 Let's Get Started
    = form_with model: @get_started_form, url: start_index_path, html: {novalidate: true}, data: {"get-started-target": "form", action: "submit->get-started#validateForm"} do |form|
      .form-row
        .col-12.col-md-8.col-lg-6
          %h4 1. Select your country
          = form.select :country_id, options_from_collection_for_select(@countries, :id, :name, @get_started_form.country_id), {include_blank: true, prompt: "Type or select an option"}, {class: "custom-select", "data-get-started-target": "countrySelect", required: true}
          .invalid-feedback.my-3 Please choose a country.
      .form-row
        .col
          %h4
            2. Select an assessment
          .form-check
            = form.radio_button :blank_assessment, false, class: "form-check-input", required: true, autocomplete: "off", checked: true
            = form.label :blank_assessment, "Most recent JEE or SPAR score", value: false, class: "form-check-label"
            %p
              %small.text-muted
                Your last registered scores are added automatically
          .form-check
            = form.radio_button :blank_assessment, true, class: "form-check-input", required: true, autocomplete: "off"
            = form.label :blank_assessment, "New JEE assessment", value: true, class: "form-check-label"
            %p
              %small.text-muted Add your own scores
      .form-row
        .col
          = form.submit "Next", class: "btn btn-primary"

app/views/start/show.html.haml
- heading_disabled_class = @get_started_form.country.present? ? "": "disabled"
.row{
  id: "get_started",
  "data-controller": "get-started",
  "data-get-started-named-ids-value": AssessmentPublication::NAMED_IDS.to_json
}
  .col
    %h1 Let's Get Started
    = form_with model: @get_started_form, url: start_path(id: params[:id]), method: :patch, data: {"get-started-target": "form", action: "submit->get-started#validateForm"}, html: {novalidate: true} do |form|
      .form-row
        .col-6
          %h4 1. Select your country
          %label= @country.name
      - if @get_started_form.blank_assessment
        .form-row
          .col
            %h4 2. Select an assessment
            = form.hidden_field :blank_assessment
            = form.label :blank_assessment, "New JEE assessment", value: true, class: "form-check-label"
            %p
              %small.text-muted Add your own scores
      - else
        .form-row
          .col
            %h4{class: heading_disabled_class}
              2. Choose your most recent assessment
            - @publications.each do |ap|
              .form-check
                = form.radio_button :assessment_type, ap.named_id, class: "form-check-input", required: true, "data-action": "get-started#selectAssessment", autocomplete: "off"
                = form.label :assessment_type, "#{ap.title} (#{ap.abbrev})", value: ap.named_id, class: "form-check-label"
                .invalid-feedback Please choose an assessment.
              .plan-by-technical-area-container{
                style: "display: none",
                "data-get-started-target": "planByTechnicalAreasContainer",
                "data-assessment-named-id": ap.named_id
              }
                %label
                  %input{
                    type: "checkbox",
                    name: "get_started_form[plan_by_technical_ids]",
                    value: 1,
                    autocomplete: "off",
                    "data-action": "get-started#toggleTechnicalAreas",
                    "data-assessment-named-id": ap.named_id
                  }
                    %em Optional:
                    Plan by technical area(s)
                .collapse{
                  "data-get-started-target": "technicalAreaCard",
                  "data-assessment-named-id": ap.named_id
                }
                  .col.card
                    .row
                      .col
                        %a{
                          href: "#",
                          "data-action": "get-started#selectAllTechnicalAreas",
                          "data-assessment-named-id": ap.named_id
                        }
                          Select all
                        |
                        %a{
                          href: "#",
                          "data-action": "get-started#deselectAllTechnicalAreas",
                          "data-assessment-named-id": ap.named_id
                        }
                          Deselect all
                    .row
                      - col1_count = ((ap.assessment_technical_areas.size + 1) / 2).floor
                      .col
                        - ap.assessment_technical_areas.take(col1_count).each do |technical_area|
                          = render "checkbox_for_technical_area", technical_area: technical_area, form: form
                      .col
                        - ap.assessment_technical_areas.drop(col1_count).each do |technical_area|
                          = render "checkbox_for_technical_area", technical_area: technical_area, form: form
            - if @country.assessment_publications.empty?
              %div{style: "height: 75px"}
        .form-row
          .col
            %h4{class: heading_disabled_class}
              3. What kind of plan are you making?
            - if @get_started_form.country.present?
              .form-check
                = form.radio_button :plan_term, 1, class: "form-check-input", required: true, autocomplete: "off"
                = form.label :plan_term, "1-year plan", value: 1, class: "form-check-label"
                %p
                  %em
                    For each indicator, increase scores by 1 level.
              .form-check
                = form.radio_button :plan_term, 5, class: "form-check-input", required: true, autocomplete: "off"
                = form.label :plan_term, "5-year plan", value: 5, class: "form-check-label"
                %p
                  %em
                    For each indicator, increase scores to demonstrated (4) or sustained (5) capacity.
                .invalid-feedback Please choose a plan.
            - else
              %div{style: "height: 75px"}
      .form-row
        .col
          %h4{class: heading_disabled_class}
            = "#{@get_started_form.blank_assessment ? 3 : 4}. Do you want to add disease specific planning? (optional)"
          - if @country.present?
            - @diseases.each do |disease|
              .form-check
                = check_box_tag "get_started_form[diseases][]", disease.id, false, {class: "form-check-input", id: "diseases_#{disease.name}", autocomplete: "off"}
                %label{for: "diseases_#{disease.name}"}
                  = "#{disease.display} planning"
          - else
            %div{style: "height: 75px"}
      .form-row
        .col-2
          = form.submit "Next", class: "btn btn-primary", "data-get-started-target": "submit"