config/routes.rb
Rails.application.routes.draw do
  authenticate :user do
    mount Avo::Engine, at: Avo.configuration.root_path
  end

  # Mock Azure Active Directory Authentication
  #
  # These routes serve two purposes.
  # 1. The named routes provide easy usage for real production views where we
  #    need to login with Azure. These are the Azure auth routes.
  # 2. When the mock is enabled, we resolve the routes to a mock controller.
  #    When the middleware MockAzureAuthMiddleware is inserted to intercept the
  #    cookie, the Azure::MockSessions controller behaves like real Azure Auth.
  #
  # These routes will never make it to the controller in production.
  # Azure will intercept the routes before they ever get to the app.

  # The constraints help prevent access when running elsewhere, e.g. Heroku.
  constraints(-> { Rails.application.config.azure_auth_mocked }) do
    scope path: "users/auth/azure", as: "azure", module: "azure" do
      post "login", to: "mock_sessions#create"
      get "logout", to: "mock_sessions#destroy", as: :logout
    end
  end

  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
  }
  get "/users/password", to: redirect("/users/password/new")

  get "/get-started", to: "start#index"
  resources :start, path: "get-started", only: %i[index create show update]
  resources :plans, only: %i[show index create update destroy]
  resources :worksheets, only: %i[show]
  resources :costsheets, only: %i[show]
  resources :reference_library_documents, only: %i[] do
    get :download
  end
  get "plan/goals/:country_name/:assessment_type(/:plan_term)",
    to: "plans#goals", as: "plan_goals"

  ##
  # static pages
  get "/assess", to: "pages#assess"
  get "/develop", to: "pages#develop"
  get "/implement", to: "pages#implement"
  get "/privacy_policy", to: "pages#privacy_policy"
  get "/reference-library",
      to: "pages#reference_library", as: "reference_library" # Benchmark Document section
  get "/document/introduction", to: "pages#introduction", as: "introduction"
  get "/document/1-national-legislation-policy-and-financing",
      to: "pages#technical_area_1", as: "technical_area_1"
  get "/document/2-ihr-coordination-communication-and-advocacy-and-reporting",
      to: "pages#technical_area_2", as: "technical_area_2"
  get "/document/3-antimicrobial-resistance",
      to: "pages#technical_area_3", as: "technical_area_3"
  get "/document/4-zoonotic-disease",
      to: "pages#technical_area_4", as: "technical_area_4"
  get "/document/5-food-safety",
      to: "pages#technical_area_5", as: "technical_area_5"
  get "/document/6-immunization",
      to: "pages#technical_area_6", as: "technical_area_6"
  get "/document/7-national-laboratory-system",
      to: "pages#technical_area_7", as: "technical_area_7"
  get "/document/8-biosafety-and-biosecurity",
      to: "pages#technical_area_8", as: "technical_area_8"
  get "/document/9-surveillance",
      to: "pages#technical_area_9", as: "technical_area_9"
  get "/document/10-human-resources",
      to: "pages#technical_area_10", as: "technical_area_10"
  get "/document/11-emergency-preparedness",
      to: "pages#technical_area_11", as: "technical_area_11"
  get "/document/12-emergency-response-operations",
      to: "pages#technical_area_12", as: "technical_area_12"
  get "/document/13-linking-public-health-and-security-authorities",
      to: "pages#technical_area_13", as: "technical_area_13"
  get "/document/14-medical-countermeasures-and-personnel-deployment",
      to: "pages#technical_area_14", as: "technical_area_14"
  get "/document/15-risk-communication",
      to: "pages#technical_area_15", as: "technical_area_15"
  get "/document/16-points-of-entry",
      to: "pages#technical_area_16", as: "technical_area_16"
  get "/document/17-chemical-events",
      to: "pages#technical_area_17", as: "technical_area_17"
  get "/document/18-radiation-emergencies",
      to: "pages#technical_area_18", as: "technical_area_18"
  get "/document/acronyms", to: "pages#acronyms", as: "acronyms"
  get "/document/glossary", to: "pages#glossary", as: "glossary"
  get "/document/acknowledgement",
      to: "pages#acknowledgement", as: "acknowledgement"

  get "/healthcheck", to: "healthchecks#index", as: "healthcheck"

  root to: "pages#home"
end

app/views/pages/_reference_document.html.haml
- if document_present?(document)
  - technical_area_ids = technical_area_texts_to_ids(@technical_areas, document.technical_areas)
  - technical_area_css_classes = ta_ids_to_css_classes(technical_area_ids)
  .document.row.no-gutters{
    class: "#{technical_area_css_classes} reference-type-#{document.reference_type_ordinal}"
  }
    .document.col.card.flex-row
      - if document.thumbnail_url.present?
        .cover-image
          = link_to reference_library_document_download_url(document), target: :_blank do
            %img{src: image_path(document.thumbnail_url), width: 160}/
      .document-about.col
        - if document.title.present?
          = link_to document.title, reference_library_document_download_url(document), target: :_blank
        - elsif document.title.present?
          .document-title
            = document.title
        - if document.author.present? || document.date.present?
          .document-byline
            = [document.author, document.date].join(", ")
        - if document.description.present?
          .document-desc
            = document.description
        - if document.relevant_pages.present?
          .document-relevant-sections
            %strong
              Relevant Section:
            = document.relevant_pages

app/views/pages/_reference_filter_by.haml
.card.reference-filter-by
  .card-header
    .tab
      Filter by
  .card-body
    %form{method: "get"}
      .form-row.flex-column
        .col
          %strong
            Technical Area
        .col
          = select_tag :technical_area, options_from_collection_for_select(@technical_areas, :text, :text, params[:technical_area]), {prompt: "Type or select an option", class: "custom-select", onchange: 'this.form.submit()', "data-reference-library-target": "technicalAreaSelect"}
      .form-row.flex-column
        .col
          %strong
            Reference Type
        .col
          - @ref_doc_types.each do |document_type|
            %input{
              type: "checkbox",
              value: document_type,
              name: "reference_types[]",
              id: document_type,
              onchange: "this.form.submit()",
              checked: params[:reference_types]&.include?(document_type)
            }/
            %label{for: document_type}
              = document_type
            .w-100

app/views/pages/acronyms.html.haml
= render layout: "layouts/benchmark_document" do
  %h1
    Acronyms
  %table{width: "100%", border: "0"}
    %tr
      %td
        %strong AEFI
      %td adverse event following immunization
    %tr
      %td
        %strong AMR
      %td antimicrobial resistance
    %tr
      %td
        %strong BTWC
      %td Biological and Toxin Weapons Convention
    %tr
      %td
        %strong EMT
      %td emergency medical team
    %tr
      %td
        %strong EOC
      %td emergency operations centre
    %tr
      %td
        %strong FAO
      %td Food and Agriculture Organization
    %tr
      %td
        %strong GLASS
      %td Global Antimicrobial Resistance Surveillance System
    %tr
      %td
        %strong GOARN
      %td Global Outbreak Alert and Response Network
    %tr
      %td
        %strong IAEA
      %td International Atomic Energy Agency
    %tr
      %td
        %strong IHR
      %td International Health Regulations
    %tr
      %td
        %strong INFOSAN
      %td International Food Safety Authorities Network
    %tr
      %td
        %strong INTERPOL
      %td International Criminal Police Organization
    %tr
      %td
        %strong IPCAT
      %td infection prevention and control (IPC) assessment tool
    %tr
      %td
        %strong IT
      %td information technology
    %tr
      %td
        %strong JEE
      %td joint external evaluation
    %tr
      %td
        %strong MCV
      %td measles-containing vaccine
    %tr
      %td
        %strong NAPHS
      %td National Action Plan for Health Security
    %tr
      %td
        %strong NCC
      %td IHR national focal point
    %tr
      %td
        %strong OIE
      %td World Organisation for Animal Health
    %tr
      %td
        %strong OPCW
      %td Organisation for the Prohibition of Chemical Weapons
    %tr
      %td
        %strong PVS
      %td performance of veterinary services
    %tr
      %td
        %strong SOP
      %td standard operating procedure
    %tr
      %td
        %strong SPAR
      %td IHR self-assessment annual reporting tool
    %tr
      %td
        %strong VPDs
      %td vaccine-preventable diseases
    %tr
      %td
        %strong WASH
      %td water, sanitation and hygiene
    %tr
      %td
        %strong WASH FIT
      %td water and sanitation for health facility improvement tool
    %tr
      %td
        %strong WHA
      %td World Health Assembly
    %tr
      %td
        %strong WHO
      %td World Health Organization

app/views/pages/assess.html.haml
= content_for :homepage do
  %nav.navbar.navbar-expand-lg
    .container.mx-auto.my-3.px-0
      %ul.navbar-nav
        %li.nav-item.mx-lg-2
          %a.nav-link.py-1.active{href: assess_path}
            ASSESS
        %li.nav-item.mx-lg-2
          %a.nav-link.text-blue.py-1{href: develop_path}
            DEVELOP
        %li.nav-item.mx-lg-2
          %a.nav-link.text-blue.py-1{href: develop_path}
            IMPLEMENT
  .section--navy.position-relative.py-4
    .position-absolute.h-100.w-100#particles-js
    .container
      .row.d-flex
        .col-sm.align-middle.my-auto
          %h1 Assess capacity
          %p.large
            Countries must assess their ability to prevent, detect and respond
            to epidemics using different approaches that provide unique
            insights into the country's risk, vulnerability and capacity
            profile for infectious disease threats.
        .col-5.m-auto= render "step_up_image"
  .section
    .container.mx-auto.my-5
      %h3 1. Assess overall preparedness capacity
      %ul
        %li
          %a{href: "https://extranet.who.int/sph/spar"}
            The States Parties Annual Reporting (SPAR)
          is a mandatory, annual, self-reporting tool to monitor progress towards full implementation of IHR.
        %li
          %a{href: "https://extranet.who.int/sph/jee"}
            The Joint External Evaluation (JEE)
          is a voluntary and comprehensive process conducted every 3-5 years to evaluate country capacity across 19 technical areas.
      %h3 2. Characterize risks and vulnerability
      %ul
        %li
          %a{href: "https://www.who.int/publications/i/item/9789240036086"}
            The Strategic Tool for Assessing Risks (STAR)
          assesses the likelihood and potential impact of public health risks to inform planning and prioritization of health emergency preparedness and disaster risk management activities.
        %li
          %a{
            href: "https://www.euro.who.int/en/health-topics/health-emergencies/publications/2009/introduction-to-health-vulnerability-and-risk-analysis-and-mapping-vram"
          }
            Vulnerability and Risk Assessment Mapping (VRAM)
          assesses health risks within a country to inform disaster risk reduction, emergency preparedness and response plans.
      %h3 3. Evaluate real-world performance
      %ul
        %li
          %a{href: "https://www.who.int/publications/i/item/WHO-WHE-CPI-2019.4"}
            After-Action Reviews (AARs)
          are qualitative evaluations of a response to a real event. For protracted events such as COVID-19, countries may use an Intra-Action Review (IAR) to inform response and preparedness planning going forward.
        %li
          %a{href: "https://extranet.who.int/sph/simulation-exercise"}
            Simulation Exercises (SimExs)
          are qualitative evaluations of simulated events to test the performance of the preparedness system in anticipation of a real event.
      %h3
        4. Identify coordination barriers between animal and human health sectors
      %ul
        %li
          %a{
            href: "https://extranet.who.int/sph/ihr-pvs-bridging-workshop#:~:text=IHR%2DPVS%20National%20Bridging%20Workshops,and%20from%20animal%20health%20services"
          }
            The One Health and IHR-PVS bridging workshops
          identify corrective measures to improve the collaboration between the two sectors in the prevention, detection and response to zoonotic disease outbreaks and other health issues.
      %p
        Each type of assessment provides a unique insight into the country's risk, vulnerability and capacity profile for infectious diseases threats.
      %p
        The WHO Benchmarks uses the SPAR and JEE as baseline data to propose benchmark actions for a high-quality National Action Plan for Health Security (NAPHS). The facilitation toolkit offers recommendations integrating the above assessments into national planning.
      %p.large
        = link_to "Next: Develop", develop_path, class: "btn btn-orange", type: "button"

app/views/pages/home.html.haml
= content_for :homepage do
  .section--blue.align-items-center
    .col-med.d-flex.text-center.flex-column.mb-4.align-items-center
      %h1.text-center
        Facilitate the planning and implementation of
        %br.d-none.d-md-inline/
        health security preparedness
  .section
    .container.mx-auto.my-5
      %h1.text-center Strengthening IHR Capacities
      %p.large.text-center
        This digital platform supports countries easily use existing assessments, benchmark recommendations and implementation tools to build IHR capacities for preparedness.
      .row.d-flex.justify-content-center.my-4
        .col-sm.my-4
          %div{style: "height:120px;"}
            = image_tag "review.svg", class: "img-fluid d-block mx-auto mb-4", alt: "Review"
          %h5 Review existing critical gaps
          %p
            Review how the various pieces of the IHR M&E framework can be implemented to reinforce preparedness in your country.
        .col-sm.my-4
          %div{style: "height:120px;"}
            = image_tag "draft.svg", class: "img-fluid d-block mx-auto mb-4", alt: "Develop"
          %h5 Develop draft plans
          %p
            Rapidly identify capacity building benchmark actions to support national priorities and NAPHS.
        .col-sm.my-4
          %div{style: "height:120px;"}
            = image_tag "reference.svg", class: "img-fluid d-block mx-auto mb-4", alt: "Reference"
          %h5 Find practical guidelines, toolkits and country examples
          %p
            Use the Reference Library to to quickly access relevant tools and guidance that are linked with capacity building actions.
      %p.large.text-center
        = link_to "Get Started", get_started_url, class: "btn btn-orange cta-btn", type: "button"
  .section--navy.position-relative.py-5
    .position-absolute.h-100.w-100#particles-js
    .container
      .row.d-flex
        .col-sm.m-auto= render "step_up_image"
        .col-sm.align-middle.my-auto
          %h1 IHR Capacity Building Stages
          .div#step-up-text
            %h3 Assess capacity
            %p
              Assessments such as JEE/SPAR to identify and evaluate a country's national preparedness capacities, identify risks and prioritize actions for capacity building to prevent, detect, and rapidly respond to public health and threats.
            %a{class: "btn btn-orange", type: "button", href: assess_path}
              Learn More

app/views/pages/reference_library.html.haml
.reference-library{"data-controller": "reference-library"}
  = link_to "Add Resource", "https://airtable.com/shrGiWYwJV7TSJNMu", class: "btn btn-primary", role: "button", style: "float: right; margin-top: 6px;"
  %h1 Reference Library
  .row.flex-wrap-reverse
    .col-lg-4.col-md-12
      = render partial: "reference_filter_by"
    .col-lg-8.col-md-12
      .result-metadata
        %p
          = link_to "Reset", reference_library_url
          %span.pipe-with-space
            |
          %strong
            Selections:
          %span#filterCriteriaDisplay
            - if params[:technical_area]
              %span.badge.badge-pill
                = params[:technical_area]
                = link_to reference_library_path(remove_technical_area_param) do
                  %svg.x-close{xmlns: "http://www.w3.org/2000/svg"}
                    %path{
                      d: "M5.646 5.646a.5.5 0 000 .708l8 8a.5.5 0 00.708-.708l-8-8a.5.5 0 00-.708 0z"
                    }
                    %path{
                      d: "M14.354 5.646a.5.5 0 010 .708l-8 8a.5.5 0 01-.708-.708l8-8a.5.5 0 01.708 0z"
                    }
            - params[:reference_types]&.each do |type|
              %span.badge.badge-pill
                = type
                = link_to reference_library_path(remove_reference_type_param(type)) do
                  %svg.x-close{xmlns: "http://www.w3.org/2000/svg"}
                    %path{
                      d: "M5.646 5.646a.5.5 0 000 .708l8 8a.5.5 0 00.708-.708l-8-8a.5.5 0 00-.708 0z"
                    }
                    %path{
                      d: "M14.354 5.646a.5.5 0 010 .708l-8 8a.5.5 0 01-.708-.708l8-8a.5.5 0 01.708 0z"
                    }
        %p
          Showing
          %span
            %b
              = @documents.count
            references
      .document-container
        - @documents.each do |document|
          = render partial: "reference_document", locals: {document: document}
  .row
    .col.p-5.h5.d-flex.justify-content-center
      = paginate @documents

app/views/pages/technical_area_13.html.haml
= render layout: "layouts/benchmark_document" do
  %h1
    13. Linking public health and security authorities
  %p
    Country conducts a rapid, multisectoral response for any event of suspected or confirmed deliberate origin, including the capacity to link public health and law enforcement, and to provide timely international assistance.
  .callout-with-icon
    .col-1.mx-auto.px-0
      = inline_svg_tag "star.svg"
    .col
      %h3
        Impact
      Development and implementation of a memorandum of understanding or other similar framework outlining roles, responsibilities and best practices for sharing relevant information among appropriate human and animal health, law enforcement and defense personnel, and validation of the memorandum of understanding through periodic exercises and simulations. Countries have systems to conduct and support joint epidemiological and criminal investigations to identify and respond to suspected biological, chemical or radiological incidents of suspected deliberate origin in collaboration with individual Biological and Toxin Weapons Convention (BTWC) of States Parties, FAO, International Atomic Energy Agency (IAEA), International Criminal Police Organization (INTERPOL), OIE, Organisation for the Prohibition of Chemical Weapons (OPCW), the United Nations Secretary-General’s Mechanism for Investigation of Alleged Use of Chemical and Biological Weapons, WHO and other relevant regional and international organizations as appropriate.
  .callout-with-icon
    .col-1.mx-auto.px-0
      = inline_svg_tag "ico-bar-chart.svg"
    .col
      %h3
        Monitoring and evaluation
      Evidence of at least one response in the previous year that effectively links public health and law enforcement, or a formal exercise or simulation involving leadership from the country’s public health and law enforcement communities.
  %hr.indicator-hr/
  %a{name: "13.1"}
  .indicator-head
    %h3
      Benchmark 13.1
    Public health and security authorities (law enforcement, border control, customs) linked during a suspect or confirmed biological, chemical or radiological event
  %p
    %strong
      Objective:
    Strengthening the linkage between public health and security authorities during potential events of national concern
  .indicator-capacity-row.first
    .head.col.bg-danger
      .level-num
        01
      .level-desc
        No capacity
    .body.col-12.col-md-9
      No legislation, relationships, protocols, memoranda of understanding or other agreements exist between public health, animal health, radiological safety, chemical safety and security authorities to address all hazards.
  .indicator-capacity-row
    .head.col.bg-warning
      .level-num
        02
      .level-desc
        Limited capacity
    .body.col-12.col-md-9
      %strong
        Actions to achieve this level:
      %ul
        %li
          Identify sectors responsible for response to potential IHR related hazards (biological, chemical and radiation).
        %li
          Identify points-of-contact to assist with the implementation of prevention, detection and response activities at government agencies across multiple sectors (such as public health, animal health, security authorities, agriculture, chemical, radiation).
        %li
          Determine roles and responsibilities for responding to various threats and other incidents of concern through a review of national response plans, policies and procedures, or other means, through an engagement meeting or other means.
        %li
          Assess risk of significant biological (and chemical or radiological) incidents of concern to the country.
        %li
          Develop triggers for sharing information on biological threats or other incidents of concern (such as chemical, radiological) with relevant multisectoral agencies.
        %li
          Establish an informal or formal communications process to share information, based on identified triggers, related to biological threats or other incidents of concern (such as chemical, radiological) among relevant multisectoral agencies (such as public health, animal health and security authorities).
        %li
          Train staff on joint risk assessment and application of triggers, and sharing of information among all sectors relevant to hazards.
  .indicator-capacity-row
    .head.col.bg-warning
      .level-num
        03
      .level-desc
        Developed capacity
    .body.col-12.col-md-9
      %strong
        Actions to achieve this level:
      %ul
        %li
          Establish communication among public health, animal health and security/law enforcement points of contact who would need to collaborate in case of a suspected intentional event.
        %li
          Identify appropriate activities (such as notifications, assessments, investigation, laboratory testing) for response to biological threats or other incidents of concern (such as chemical, radiological), which will be covered by a written protocol or memorandum of understanding between sectors.
        %li
          Develop logistical plans to include multisectoral agencies, including if appropriate, law enforcement, in the public health EOC.
        %li
          Determine sample collection, transport, storage, security and testing requirements among relevant sectors (i.e. public health, security authorities, agriculture) for biological threats and other incidents of concern (such as chemical, radiological).
        %li
          Finalize a written protocol or memorandum of understanding that formalizes and institutionalizes interactions between relevant multisectoral agencies (public health, animal health and security authorities).
        %li
          Develop SOPs defining the process and communication mechanisms for assessing and responding to suspected international events.
        %li
          Develop training curriculum using country-specific content (such as regulations/authorities, agency roles/responsibilities and case studies).
  .indicator-capacity-row
    .col.head.bg-success
      .level-num
        04
      .level-desc
        Demonstrated capacity
    .body.col-12.col-md-9
      %strong
        Actions to achieve this level:
      %ul
        %li
          Conduct regular training in relevant sectors.
        %li
          Conduct at least one public health emergency response or exercise per year that includes appropriate information sharing between public health and security authorities using the formal protocol or memorandum of understanding.
        %li
          Document findings of the response or exercise, highlight the gaps and best practices, and adjust protocols as appropriate.
        %li
          Conduct joint training of public health, animal health and security authorities to orient, exercise and institutionalize knowledge of memorandum of understanding and other agreements related to all hazards.
  .indicator-capacity-row
    .head.col.bg-success
      .level-num
        05
      .level-desc
        Sustainable capacity
    .body.col-12.col-md-9
      %strong
        Actions to achieve this level:
      %ul
        %li
          Document conduction of regular joint training/exercise programmes at national, intermediate and local levels for public health, animal health and security authorities to orient, exercise and institutionalize the knowledge of memorandum of understanding and other agreements related to all hazards.
        %li
          Expand the joint risk assessment, exchange of information and reporting to all levels (national, intermediate and local levels).
        %li
          Conduct an evaluation to determine whether information about events of joint concern is shared in a timely and effective manner at national, intermediate and local levels as outlined in formal memoranda of understanding or other agreements/protocols, and that the response is appropriate and effective, and corrective action is taken based on this evaluation.
  %h3 Tools:
  %ul
    %li
      WHO–OIE operational framework for good governance at the human¬–animal interface:
      %a{
        href: "http://www.oie.int/fileadmin/Home/fr/Media_Center/docs/pdf/WHO_OIE_Operational_Framework_Final2.pdf",
        target: "_blank"
      }
        Bridging WHO and OIE tools for the assessment of national capacities.
      WHO and OIE; 2014.
    %li
      Terrestrial animal health code.
      %a{
        href: "http://www.oie.int/index.php?id=169&L=0&htmfile=chapitre_vet_legislation.htm",
        target: "_blank"
      }
        Chapter 3.4 Veterinary legislation.
      World Organisation for Animal Health; 2016.
    %li
      %a{
        href: "https://www.opcw.org/fileadmin/OPCW/CWC/CWC_en.pdf",
        target: "_blank"
      }
        Convention on the prohibition of the development, production, stockpiling and use of chemical weapons and on their destruction.
      The Hague: Organisation for the Prohibition of Chemical Weapons.
    %li
      Treaty on the non-proliferation of nuclear weapons. International Atomic Energy Agency [
      %a{
        href: "https://www.iaea.org/sites/default/files/publications/documents/infcircs/1970/infcirc140.pdf",
        target: "_blank"
      }
        information circular
      ] INFCIRC/140, 22 April 1970.
    %li
      %a{
        href: "https://www.fbi.gov/file-repository/joint-criminal-and-epidemiological-investigations-handbook-2016-international-edition/view",
        target: "_blank"
      }
        Joint Criminal and Epidemiological Investigations Handbook 2016.
      International Edition.