config/routes.rb
Rails.application.routes.draw do
  authenticate :user do
    mount Avo::Engine, at: Avo.configuration.root_path
  end

  # Mock Azure Active Directory Authentication
  #
  # These routes serve two purposes.
  # 1. The named routes provide easy usage for real production views where we
  #    need to login with Azure. These are the Azure auth routes.
  # 2. When the mock is enabled, we resolve the routes to a mock controller.
  #    When the middleware MockAzureAuthMiddleware is inserted to intercept the
  #    cookie, the Azure::MockSessions controller behaves like real Azure Auth.
  #
  # These routes will never make it to the controller in production.
  # Azure will intercept the routes before they ever get to the app.

  # The constraints help prevent access when running elsewhere, e.g. Heroku.
  constraints(-> { Rails.application.config.azure_auth_mocked }) do
    scope path: "users/auth/azure", as: "azure", module: "azure" do
      post "login", to: "mock_sessions#create"
      get "logout", to: "mock_sessions#destroy", as: :logout
    end
  end

  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
  }
  get "/users/password", to: redirect("/users/password/new")

  get "/get-started", to: "start#index"
  resources :start, path: "get-started", only: %i[index create show update]
  resources :plans, only: %i[show index create update destroy]
  resources :worksheets, only: %i[show]
  resources :costsheets, only: %i[show]
  resources :reference_library_documents, only: %i[] do
    get :download
  end
  get "plan/goals/:country_name/:assessment_type(/:plan_term)",
    to: "plans#goals", as: "plan_goals"

  ##
  # static pages
  get "/assess", to: "pages#assess"
  get "/develop", to: "pages#develop"
  get "/implement", to: "pages#implement"
  get "/privacy_policy", to: "pages#privacy_policy"
  get "/reference-library",
      to: "pages#reference_library", as: "reference_library" # Benchmark Document section
  get "/document/introduction", to: "pages#introduction", as: "introduction"
  get "/document/1-national-legislation-policy-and-financing",
      to: "pages#technical_area_1", as: "technical_area_1"
  get "/document/2-ihr-coordination-communication-and-advocacy-and-reporting",
      to: "pages#technical_area_2", as: "technical_area_2"
  get "/document/3-antimicrobial-resistance",
      to: "pages#technical_area_3", as: "technical_area_3"
  get "/document/4-zoonotic-disease",
      to: "pages#technical_area_4", as: "technical_area_4"
  get "/document/5-food-safety",
      to: "pages#technical_area_5", as: "technical_area_5"
  get "/document/6-immunization",
      to: "pages#technical_area_6", as: "technical_area_6"
  get "/document/7-national-laboratory-system",
      to: "pages#technical_area_7", as: "technical_area_7"
  get "/document/8-biosafety-and-biosecurity",
      to: "pages#technical_area_8", as: "technical_area_8"
  get "/document/9-surveillance",
      to: "pages#technical_area_9", as: "technical_area_9"
  get "/document/10-human-resources",
      to: "pages#technical_area_10", as: "technical_area_10"
  get "/document/11-emergency-preparedness",
      to: "pages#technical_area_11", as: "technical_area_11"
  get "/document/12-emergency-response-operations",
      to: "pages#technical_area_12", as: "technical_area_12"
  get "/document/13-linking-public-health-and-security-authorities",
      to: "pages#technical_area_13", as: "technical_area_13"
  get "/document/14-medical-countermeasures-and-personnel-deployment",
      to: "pages#technical_area_14", as: "technical_area_14"
  get "/document/15-risk-communication",
      to: "pages#technical_area_15", as: "technical_area_15"
  get "/document/16-points-of-entry",
      to: "pages#technical_area_16", as: "technical_area_16"
  get "/document/17-chemical-events",
      to: "pages#technical_area_17", as: "technical_area_17"
  get "/document/18-radiation-emergencies",
      to: "pages#technical_area_18", as: "technical_area_18"
  get "/document/acronyms", to: "pages#acronyms", as: "acronyms"
  get "/document/glossary", to: "pages#glossary", as: "glossary"
  get "/document/acknowledgement",
      to: "pages#acknowledgement", as: "acknowledgement"

  get "/healthcheck", to: "healthchecks#index", as: "healthcheck"

  root to: "pages#home"
end

app/models/plan.rb
# This consists of the assessment goals
# organized by Technical Area and Benchmark Indicator. The action_map
# field is an ActionMap object.
class Plan < ApplicationRecord
  ASSESSMENT_TYPES = [
    1, # jee1
    2, # spar_2018
    3 # jee2
  ].freeze

  # TODO: update this implementation once the assessments page is modernized
  ASSESSMENT_TYPE_NAMED_IDS = %w[jee1 spar_2018 jee2].freeze
  TERM_TYPES = [100, 500] # 100 is 1-year, 500 is 5-year
  PURGEABLE_WEEKS = 2.freeze
  include PlanBuilder

  belongs_to :assessment
  belongs_to :user, optional: true
  has_many :goals, class_name: "PlanGoal", dependent: :destroy
  has_many :plan_actions, dependent: :destroy
  has_many :benchmark_indicator_actions, through: :plan_actions
  has_many :plan_diseases
  has_many :diseases, through: :plan_diseases, dependent: :destroy
  has_many :reference_library_documents, through: :benchmark_indicator_actions

  delegate :alpha3, to: :country
  delegate :jee?, :spar?, :type_description, to: :assessment

  def self.deep_load(id)
    includes(
        :goals,
        {
          plan_actions: {
            benchmark_indicator_action: :reference_library_documents
          }
        }
      )
      .where(id: id)
      .first
  end

  scope :purgeable,
        -> {
          where("updated_at < ?", PURGEABLE_WEEKS.weeks.ago).where(user: nil)
        }

  validates :assessment, presence: true
  validates :name, presence: true
  validates :term, inclusion: TERM_TYPES

  def self.purge_old_plans!(dry_run: false)
    dry_run ? purgeable : purgeable.delete_all
  end

  def is_5_year?
    term.eql?(TERM_TYPES.second)
  end

  def action_ids
    benchmark_indicator_actions.pluck(:id)
  end

  def update!(name:, benchmark_action_ids:)
    current_action_ids = benchmark_indicator_action_ids

    # Use +Set+ to avoid adding duplicates.
    current_action_id_set = current_action_ids.to_set
    benchmark_action_id_set = benchmark_action_ids.to_set

    # 1st, remove any needed.
    remove_action_ids = (current_action_id_set - benchmark_action_id_set).to_a
    remove_actions =
      plan_actions.where(benchmark_indicator_action_id: remove_action_ids).all
    remove_actions.each(&:destroy)

    # 2nd, add any needed.
    add_action_ids = (benchmark_action_id_set - current_action_id_set).to_a
    add_action_ids.each do |benchmark_action_id|
      benchmark_action = BenchmarkIndicatorAction.find(benchmark_action_id)
      plan_action = PlanAction.new_for_benchmark_action benchmark_action
      plan_action.plan = self
      plan_actions << plan_action
    end

    # lastly, now that the associations are handled, perform a basic update
    super name: name
  end

  # @return an Array of benchmark_indicator_action.id Integers
  #   sorted for readability
  def benchmark_indicator_action_ids
    plan_actions.map(&:benchmark_indicator_action).map(&:id).sort
  end

  def goal_for(benchmark_indicator:)
    goals.detect do |goal|
      goal.benchmark_indicator_id.eql?(benchmark_indicator.id)
    end
  end

  def goal_value_for(benchmark_indicator:)
    goals.detect do |goal|
      goal.benchmark_indicator_id.eql?(benchmark_indicator.id)
    end&.value
  end

  ##
  # arg is a BenchmarkIndicatorAction
  def actions_for(benchmark_indicator)
    plan_actions.to_a.select do |plan_action|
      plan_action.benchmark_indicator_id.eql?(benchmark_indicator.id)
    end
  end

  ##
  # @return an Array of BenchmarkIndicatorAction instances
  # this could be an opportunity for performance improvement since the plan/show
  # view calls this method for each benchmark indicator. perhaps switch it to
  # use Ajax instead of embedding the page within each indicator.
  def excluded_actions_for(benchmark_indicator)
    # note that "all possible" is scoped within the given benchmark_indicator
    all_possible_actions = benchmark_indicator.actions
    included_actions =
      plan_actions
        .where(benchmark_indicator_action_id: all_possible_actions)
        .map(&:benchmark_indicator_action)
    (all_possible_actions.to_set - included_actions.to_set).to_a
  end

  def current_and_target_scores
    goals.reduce({}) do |cats, goal|
      cats[goal.benchmark_indicator_id] = [goal.assessed_score, goal.value]
      cats
    end
  end

  def as_json(options = {})
    super(
      options.reverse_merge(
        only: %i[id name term],
        include: [:diseases],
        methods: %i[action_ids disease_ids]
      )
    )
  end
end

app/models/plan_action.rb
class PlanAction < ApplicationRecord
  belongs_to :plan
  belongs_to :benchmark_indicator_action
  belongs_to :benchmark_indicator
  belongs_to :benchmark_technical_area

  default_scope do
    includes(:benchmark_indicator_action).order(
      "benchmark_indicator_actions.level",
      "benchmark_indicator_actions.sequence"
    )
  end

  delegate :text, :sequence, to: :benchmark_indicator_action

  def self.new_for_benchmark_action(benchmark_indicator_action)
    new(
      benchmark_indicator_action: benchmark_indicator_action,
      benchmark_indicator_id: benchmark_indicator_action.benchmark_indicator_id,
      benchmark_technical_area_id:
        benchmark_indicator_action.benchmark_technical_area_id
    )
  end
end

app/controllers/plan_controller.rb
class PlanController < ApplicationController
  def show
    @benchmarks = BenchmarksFixture.new
    @plan = Plan.find_by_id!(params.fetch(:id))
  end

  def index
    @plans = Plan.all
  end

  def update
    plan = Plan.find_by_id!(params.fetch(:id))
    plan.update!(
      name: plan_params.fetch(:name),
      activity_map: JSON.parse(plan_params.fetch(:activity_map))
    )
    redirect_to action: 'index'
  end

  private

  def plan_params
    params.require(:plan).permit(:name, :activity_map)
  end
end

app/controllers/plans_controller.rb
# Handle the plans model and the worksheet.
#
# Plans are typically created from the GoalsController, but are displayed,
# edited, deleted, etc. from here. This is unusual for a REST app, but plans
# are not really created from a plan sheet itself, but from the concept of a
# set of Goals.
#
# Otherwise, updates, deletes, and shows work as expected.
#
# The Index operation (GET /plans/) displays the list of plans owned by the
# user, and populates dropdown menus for starting a new plan.
#
# An unauthenticated user may get to this stage. This user is still allowed to
# edit the draft plan they have created, and the plan will be associated with
# their browser session. They'll be prompted to log in when they try to save
# the draft plan. After login (even if an account creation is involved), the
# draft plan will be attached to their account.
class PlansController < ApplicationController # workaround for XHR being unable to detect a redirect. JS handles this on the client.
  GET_STARTED_REDIRECT_KEY = "Get-Started-Redirect-To:"

  before_action :authenticate_user!, only: %i[index]
  before_action :check_ownership, except: %i[get_started goals index create]

  ##
  # the purpose of this action is to edit goal values for a plan's indicators
  def goals
    assessment_type = params[:assessment_type]
    country_name = params[:country_name]
    technical_area_ids = params[:areas].to_s.split("-")
    @disease_ids = params[:diseases]
    country = Country.find_by_name country_name
    @publication = AssessmentPublication.find_by_named_id assessment_type
    if country.present? && @publication.present?
      @assessment =
        Assessment.deep_load(country.try(:alpha3), @publication.try(:id))
    end
    if @assessment.blank?
      render "assessment_not_found"
      return
    end
    @plan =
      Plan.new_from_assessment(
        assessment: @assessment,
        technical_area_ids: technical_area_ids,
        is_5_year_plan: params[:plan_term]&.start_with?("5")
      )
  end

  # TODO: test coverage for the session state part
  def create
    assessment = Assessment.find(plan_create_params.fetch(:assessment_id))
    disease_ids = plan_create_params.fetch(:disease_ids).to_s.split("-")

    if plan_create_params[:indicators].values.map(&:to_i).any?(&:zero?)
      flash[:alert] = "Every score and goal must be 1 or higher."
      return redirect_back fallback_location: root_path
    end

    @plan =
      Plan.create_from_goal_form(
        indicator_attrs: plan_create_params.fetch(:indicators),
        assessment: assessment,
        is_5_year_plan: plan_create_params.fetch(:term).start_with?("5"),
        plan_name: "#{assessment.country.name} draft plan",
        disease_ids: disease_ids,
        user: current_user
      )
    unless @plan.persisted?
      flash[:notice] = "Could not save your plan, something went wrong."
      redirect_back fallback_location: root_path
      return
    end
    session[:plan_id] = @plan.id unless current_user
    redirect_to @plan
  rescue Exceptions::InvalidDiseasesError => e
    flash[:notice] = e.message
    redirect_back fallback_location: root_path
  end

  def show
    benchmark_document = BenchmarkDocument.new
    @benchmark_technical_areas = benchmark_document.technical_areas
    @benchmark_indicators = benchmark_document.indicators
    @all_actions = benchmark_document.actions
    @diseases = Disease.all
    @nudges_by_action_type_json =
      File.read(
        Rails.root.join("app", "fixtures", "nudges_for_action_types.json")
      )
    @plan = Plan.deep_load(params.fetch(:id))
  end

  def update
    plan = Plan.find_by_id!(params.fetch(:id))
    benchmark_action_ids =
      JSON.parse(plan_update_params.fetch(:benchmark_action_ids))
    name = plan_update_params.fetch(:name)
    plan.update!(name: name, benchmark_action_ids: benchmark_action_ids)
    redirect_to plans_path
  end

  def index
    if session[:plan_id]
      # As a compromise, when azure login completes we arrive here without
      # hitting the registrations controller which would save the plan.
      # This is a no-op without a session stored plan.
      current_user.plans << Plan.find(session[:plan_id])
      session[:plan_id] = nil
    end
    @plans = current_user.plans.order(updated_at: :desc)
  end

  def destroy
    plan = Plan.find_by_id!(params.fetch(:id))
    plan.destroy
    flash[:alert] = "Deleted #{plan.name}"
    redirect_to plans_path
  end

  private

  def alert_and_redirect
    flash[:alert] = "You are not allowed to access this plan"
    redirect_to root_path
  end

  def check_ownership
    plan_id = params.fetch(:id).to_i

    if current_user
      alert_and_redirect if current_user.plan_ids.exclude?(plan_id)
    else
      alert_and_redirect unless plan_id == session[:plan_id]
    end
  end

  def plan_create_params
    params
      .require(:plan)
      .permit(:assessment_id, :term, :disease_ids, indicators: {})
  end

  def plan_update_params
    params.require(:plan).permit(:id, :name, :benchmark_action_ids)
  end

  def goal_params
    params.require(:goal_form).permit!
  end
end

app/views/plans/_country_selection_modal.html.erb
<div
    class="modal"
    tabindex="-1"
    role="dialog"
    id="joint-country-selection-modal"
  >
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title display-header mx-4">
          LET'S GET STARTED!
        </h1>
        <button
          type="button"
          class="close"
          data-dismiss="modal"
          aria-label="Close"
        >
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <div class="modal-body mx-4">
        <p>
          Our plans are comprised of activities based off of the gap between
          the capacity score and step up score.
        </p>

        <p>
          You can create a plan from the Joint External Evaluation (JEE) or
          State Party Self-Assessment Annual Reporting (SPAR) scores.
        </p>

        <p>
          If the country hasn’t done either assessment, you can create a plan
          from technical areas.
        </p>

        <%= form_tag '/country_select', id: "assessment-select-menu" do %>
          <%= hidden_field_tag "country", nil, data: { target: "joint-country-select.selectedCountryModal" } %>
          <div class="input-group">
            <%= select_tag "country",
              options_from_collection_for_select(@countries, 'name', 'name'),
              class: "custom-select",
              data: { target: "joint-country-select.selectedCountry",
                      action: "joint-country-select#select_country" }
            %>
          <div class="input-group mb-2">
            <%= select_tag "assessment_type",
              options_from_collection_for_select([], 'assessment_type', 'assessment_type'),
              class: "custom-select",
              data: { target: "joint-country-select.assessmentTypes" } %>
          </div>
          <%= button_tag "Next", type: :submit, class: "btn btn-primary w-100" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/plans/_instructions.html.erb
<p>
  <span>
    <% if @plan.jee? %>
      The Joint External Evaluation (JEE) scores are pre-populated from WHO published <%= link_to "reports", "https://www.who.int/ihr/procedures/mission-reports/en/", target: "_blank" %>. The goals are pre-populated by one step up.  We suggest one step up for strong short term planning, however, you can change the goal based on the priorities and resources of your country. 
    <% elsif @plan.spar? %>
      The SPAR scores are pre-populated from WHO published <%= link_to "data", "https://extranet.who.int/e-spar", target: "_blank" %>. The goals are pre-populated by one step up.  We suggest one step up for strong short term planning, however, you can change the goal based on the priorities and resources of your country. 
    <% else %>
      The scores are pre-populated from WHO published <%= link_to "SPAR data", "https://extranet.who.int/e-spar", target: "_blank" %>. The goals are pre-populated by one step up. Countries without SPAR data are defaulted to a score of 1 for all indicators.
    <% end %>
  </span>
</p>
  
<p>*You can change the score if it is outdated, as measured by a formal assessment process.</p>

app/views/plans/_plan_form.html.erb
<div class="row bg-dark-blue py-4 px-0 full-width stick-to-top text-white">

    <div class="col-10 offset-1 row justify-content-between">

      <div style="height: 60px;">
        <%= form_for @plan, class: "needs-validation", novalidate: true, data: { target: "plan.form" } do |f| %>
          <%= f.hidden_field :activity_map, value: @plan.activity_map.to_json, data: {
              target: "plan.activityMap"}, autocomplete: "off" %>
          <div class="form-group alt-header" style="min-width: 200px;">
            <%= f.text_field :name, data: { target: "plan.name", action: "change->plan#validateName" }, class: "form-control", required: true %>
            <div class="invalid-feedback">
              Cannot be empty
            </div>
          </div>
        <% end %>
      </div>

      <div style="min-width: 140px;">
        <%= submit_tag "Save Plan", data: { target: "plan.submit", action: "plan#submit"}, class: "btn btn-orange w-100 align-self-center" %>
      </div>

    </div>

</div>

app/views/plans/_validated_field.html.erb
<% field_name = is_goal ? "plan[indicators][#{named_id}_goal]": "plan[indicators][#{named_id}]" %>
<div class="form-group">
  <%= number_field_tag field_name, value,
    data: { action: "change->score-and-goal#validatePair",
            goal: is_goal,
            score_and_goal_target: is_goal ? "goal": "score",
            toggle: "tooltip",
            placement: "top",
          },
    class: "form-control w-70px color-score-#{value}",
    required: true %>
</div>

app/views/plans/assessment_not_found.html.haml
.col
  %h2
    = "There is no \"#{params[:assessment_type]}\" assessment available for #{params[:country_name]}."

app/views/plans/get_started.html.haml
- heading_disabled_class = @get_started_form.country.present? ? "": "disabled"
.row{id: "get_started",
  "data-controller": "get-started",
  "data-get-started-redirect-key": @redirect_key,
  "data-get-started-named-ids": AssessmentPublication::NAMED_IDS.to_json}
  .col

    %h1 Let's Get Started

    = form_with model: @get_started_form,
      url: get_started_url, method: :POST,
      data: {target: "get-started.form", action: "submit->get-started#validateForm"},
      html: {novalidate: true} do |form|
      .form-row
        .col-6
          %h4 1. Select your country
          = form.select :country_id,
            options_from_collection_for_select(@countries, :id, :name, @get_started_form.country_id),
            {include_blank: true, prompt: "Type or select an option"},
            {class: "custom-select", "data-target": "get-started.countrySelect", required: true}
          .invalid-feedback.my-3 Please choose a country.

      .form-row
        .col
          %h4{class: heading_disabled_class} 2. Choose your most recent assessment
          - if @get_started_form.country.present?

            - if @get_started_form.country.has_jee1?
              .form-check
                = form.radio_button :assessment_type, AssessmentPublication::NAMED_IDS.first,
                  class: "form-check-input", required: true,
                  "data-action": "get-started#selectAssessmentJee1"
                = form.label :assessment_type, "Joint External Evaluation (JEE)", value: AssessmentPublication::NAMED_IDS.first,
                  class: "form-check-label"
                .invalid-feedback Please choose an assessment.
              .plan-by-technical-area-container{"data-target": "get-started.planByTechnicalAreasContainerForJee1", style: "display: none"}
                %label
                  %input{type: "checkbox", name: "get_started_form[plan_by_technical_ids]", value: 1, "data-action": "get-started#toggleTechnicalAreasForJee1"}
                    %em Optional:
                    Plan by technical area(s)
                .collapse{"data-target": "get-started.cardOfTechnicalAreasForJee1"}
                  .col.card
                    .row
                      .col
                        %a{href: "#", "data-action": "get-started#selectAllTechnicalAreasForJee1"} Select all
                        |
                        %a{href: "#", "data-action": "get-started#deselectAllTechnicalAreasForJee1"} Deselect all
                    .row
                      - col1_count_for_jee1 = ((@technical_areas_jee1.size + 1) / 2).floor
                      .col
                        - @technical_areas_jee1.take(col1_count_for_jee1).each do |technical_area|
                          = render "checkbox_for_technical_area", technical_area: technical_area, form: form
                      .col
                        - @technical_areas_jee1.drop(col1_count_for_jee1).each do |technical_area|
                          = render "checkbox_for_technical_area", technical_area: technical_area, form: form


            - if @get_started_form.country.has_spar_2018?
              .form-check
                = form.radio_button :assessment_type, AssessmentPublication::NAMED_IDS.second,
                  class: "form-check-input", required: true,
                  "data-action": "get-started#selectAssessmentSpar2018"
                = form.label :assessment_type, "State Party Annual Report (SPAR)", value: AssessmentPublication::NAMED_IDS.second,
                  class: "form-check-label"
                .invalid-feedback Please choose an assessment.
              .plan-by-technical-area-container{"data-target": "get-started.planByTechnicalAreasContainerForSpar2018", style: "display: none"}
                %label
                  %input{type: "checkbox", name: "get_started_form[plan_by_technical_ids]", value: 1, "data-action": "get-started#toggleTechnicalAreasForSpar2018"}
                    %em Optional:
                    Plan by technical area(s)
                .collapse{"data-target": "get-started.cardOfTechnicalAreasForSpar2018"}
                  .col.card
                    .row
                      .col
                        %a{href: "#", "data-action": "get-started#selectAllTechnicalAreasForSpar2018"} Select all
                        |
                        %a{href: "#", "data-action": "get-started#deselectAllTechnicalAreasForSpar2018"} Deselect all
                    .row
                      - col1_count_for_spar2018 = ((@technical_areas_spar_2018.size + 1) / 2).floor
                      .col
                        - @technical_areas_spar_2018.take(col1_count_for_spar2018).each do |technical_area|
                          = render "checkbox_for_technical_area", technical_area: technical_area, form: form
                      .col
                        - @technical_areas_spar_2018.drop(col1_count_for_spar2018).each do |technical_area|
                          = render "checkbox_for_technical_area", technical_area: technical_area, form: form

          - else
            %div{style: "height: 75px"}

      .form-row
        .col
          %h4{class: heading_disabled_class} 3. What kind of plan are you making?
          - if @get_started_form.country.present?
            .form-check
              = form.radio_button :plan_term, 1, class: "form-check-input", required: true
              = form.label :plan_term, "1 year plan", value: 1, class: "form-check-label"
              %p
                %em
                  For each indicator, increase scores by 1 level.
            .form-check
              = form.radio_button :plan_term, 5, class: "form-check-input", required: true
              = form.label :plan_term, "5 year plan", value: 5, class: "form-check-label"
              %p
                %em
                  For each indicator, increase scores to demonstrated (4) or sustained (5) capacity.
              .invalid-feedback Please choose a plan.
          - else
            %div{style: "height: 75px"}

      .form-row
        .col
          %h4{class: heading_disabled_class} 4. Do you want to add disease specific planning?
          - if @get_started_form.country.present?
            - @diseases.each do |disease|
              .form-check
                = check_box_tag "get_started_form[diseases][]", disease.id, false,
                  {class: "form-check-input",
                    id: "diseases_#{disease.name}"}
                %label{for: "diseases_#{disease.name}"}
                  = "Optional: #{disease.display} planning"
          - else
            %div{style: "height: 75px"}

      .form-row
        .col-2
          = form.submit "Next",
            class: "btn btn-primary",
            "data-target": "get-started.submit"

app/views/plans/index.html.erb
<div class="mb-4">
  <div class="row">
    <div class="col">
      <h1>WELCOME</h1>
    </div>
    <div class="col my-auto text-right">
      <%= link_to "CREATE PLAN", get_started_url, class: "btn btn-success", role: "button" %>
    </div>
  </div>

  <div class="row no-gutters">
    <% if @plans.length > 0 %>
      <div class="col-12">
        <div class="row d-none d-md-flex">
          <div class="col-7 col-md-4"><h3 class="ml-3">Saved Plans</h3></div>
          <div class="col-5 col-md-auto text-right"><h3>Last Revised</h3></div>
        </div>
        <% @plans.each do |plan| %>
          <div class="row py-2 p-md-3 border-bottom position-relative plan-row">
            <div class="delete-banner mt-n2 mt-md-n3 ml-md-n3 p-2 pb-3 flex-column flex-md-row align-items-center d-flex confirm-delete-enter">
              <div class="col d-flex flex-column align-items-left justify-content-center">
                <h4 class="my-2">Remove this plan?</h4>
                <p>This will permanently remove the plan &ldquo;<%= plan.name %>&rdquo;.</p>
              </div>
              <div class="col flex-grow-0 d-flex justify-content-end">
                <%= button_to plan_path(plan.id), method: :delete, class: "btn btn-remove mx-2 px-3 py-2" do %>
                  Remove
                <% end %>
                </button>
                <button class="btn btn-cancel x-2 px-3 py-2">
                  Cancel
                </button>
              </div>
            </div>

            <div class="col-7 col-md-4"><b><%= link_to plan.name, plan, data: { turbo: false } %></b></div>
            <div class="col-5 col-md-auto text-right"><%= plan.updated_at.strftime("%B %d, %Y") %></div>
            <div class="col-12 col-md-5 ml-md-auto mt-1 mt-md-0 d-flex justify-content-between">
              <%= link_to costsheet_path(plan.id), data: { turbo: false } do %>
                <%= inline_svg_tag "ico-download.svg" %>
                Download <span class="d-none d-lg-inline">Draft Plan</span>
              <% end %>
              <%= link_to worksheet_path(plan.id), data: { turbo: false } do %>
                <%= inline_svg_tag "ico-print.svg" %>
                Print <span class="d-none d-lg-inline">Worksheets</span>
              <% end %>
              <%= link_to plan_path(plan.id), class: "plan-delete", method: :delete, data: {
                confirm: "Are you sure you want to delete the plan '#{plan.name}'?"
              } do %>
              <img src="/delete-button.svg" alt="Delete this plan" />
              Delete
            <% end %>
            </div>
          </div>
        <% end %>
      </div>

      <div class="col-12">
        <h1 class="tips-header">You have your Draft 0.1 NAPHS plan. Now what?</h1>
        <div class="row no-gutters bg-light-gray border border-gray p-4 mb-3">
          <div class="col flex-grow-0 pr-3"><%= image_tag "pad.svg" %> </div>
          <div class="col"><span>Share it with individuals involved in the development and implementation of NAPHS to get their feedback and help consolidate areas where appropriate.</span></div>
        </div>
        <div class="row no-gutters bg-light-gray border border-gray p-4 mb-3">
          <div class="col flex-grow-0 pr-3"><%= image_tag "people.svg" %></div>
          <div class="col"><span>Then, plan an in-person workshop for discussion and validation with your multi-sectoral group.</span></div>
        </div>
        <div class="row no-gutters bg-light-gray border border-gray p-4 mb-3">
          <div class="col flex-grow-0 pr-3"><%= image_tag "book.svg" %></div>
          <div class="col"><span>Ready to implement? Check out our Reference Library that has global best practices and case studies to help you plan and implement actions successfully.</span></div>
        </div>
      </div>
  </div>
<% else %>
  <div class="col p-5 border text-center">
    You haven't started any plans yet
  </div>
<% end %>
</div>
</div>