config/routes.rb
Rails.application.routes.draw do
  authenticate :user do
    mount Avo::Engine, at: Avo.configuration.root_path
  end

  # Mock Azure Active Directory Authentication
  #
  # These routes serve two purposes.
  # 1. The named routes provide easy usage for real production views where we
  #    need to login with Azure. These are the Azure auth routes.
  # 2. When the mock is enabled, we resolve the routes to a mock controller.
  #    When the middleware MockAzureAuthMiddleware is inserted to intercept the
  #    cookie, the Azure::MockSessions controller behaves like real Azure Auth.
  #
  # These routes will never make it to the controller in production.
  # Azure will intercept the routes before they ever get to the app.

  # The constraints help prevent access when running elsewhere, e.g. Heroku.
  constraints(-> { Rails.application.config.azure_auth_mocked }) do
    scope path: "users/auth/azure", as: "azure", module: "azure" do
      post "login", to: "mock_sessions#create"
      get "logout", to: "mock_sessions#destroy", as: :logout
    end
  end

  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
  }
  get "/users/password", to: redirect("/users/password/new")

  get "/get-started", to: "start#index"
  resources :start, path: "get-started", only: %i[index create show update]
  resources :plans, only: %i[show index create update destroy]
  resources :worksheets, only: %i[show]
  resources :costsheets, only: %i[show]
  resources :reference_library_documents, only: %i[] do
    get :download
  end
  get "plan/goals/:country_name/:assessment_type(/:plan_term)",
    to: "plans#goals", as: "plan_goals"

  ##
  # static pages
  get "/assess", to: "pages#assess"
  get "/develop", to: "pages#develop"
  get "/implement", to: "pages#implement"
  get "/privacy_policy", to: "pages#privacy_policy"
  get "/reference-library",
      to: "pages#reference_library", as: "reference_library" # Benchmark Document section
  get "/document/introduction", to: "pages#introduction", as: "introduction"
  get "/document/1-national-legislation-policy-and-financing",
      to: "pages#technical_area_1", as: "technical_area_1"
  get "/document/2-ihr-coordination-communication-and-advocacy-and-reporting",
      to: "pages#technical_area_2", as: "technical_area_2"
  get "/document/3-antimicrobial-resistance",
      to: "pages#technical_area_3", as: "technical_area_3"
  get "/document/4-zoonotic-disease",
      to: "pages#technical_area_4", as: "technical_area_4"
  get "/document/5-food-safety",
      to: "pages#technical_area_5", as: "technical_area_5"
  get "/document/6-immunization",
      to: "pages#technical_area_6", as: "technical_area_6"
  get "/document/7-national-laboratory-system",
      to: "pages#technical_area_7", as: "technical_area_7"
  get "/document/8-biosafety-and-biosecurity",
      to: "pages#technical_area_8", as: "technical_area_8"
  get "/document/9-surveillance",
      to: "pages#technical_area_9", as: "technical_area_9"
  get "/document/10-human-resources",
      to: "pages#technical_area_10", as: "technical_area_10"
  get "/document/11-emergency-preparedness",
      to: "pages#technical_area_11", as: "technical_area_11"
  get "/document/12-emergency-response-operations",
      to: "pages#technical_area_12", as: "technical_area_12"
  get "/document/13-linking-public-health-and-security-authorities",
      to: "pages#technical_area_13", as: "technical_area_13"
  get "/document/14-medical-countermeasures-and-personnel-deployment",
      to: "pages#technical_area_14", as: "technical_area_14"
  get "/document/15-risk-communication",
      to: "pages#technical_area_15", as: "technical_area_15"
  get "/document/16-points-of-entry",
      to: "pages#technical_area_16", as: "technical_area_16"
  get "/document/17-chemical-events",
      to: "pages#technical_area_17", as: "technical_area_17"
  get "/document/18-radiation-emergencies",
      to: "pages#technical_area_18", as: "technical_area_18"
  get "/document/acronyms", to: "pages#acronyms", as: "acronyms"
  get "/document/glossary", to: "pages#glossary", as: "glossary"
  get "/document/acknowledgement",
      to: "pages#acknowledgement", as: "acknowledgement"

  get "/healthcheck", to: "healthchecks#index", as: "healthcheck"

  root to: "pages#home"
end

app/views/layouts/_benchmark_document.html.haml
.benchmark-document
  .row
    .col
      .row
        .col
          = yield
    .col-lg-4.col-md-12.sidebar-right.mt-5
      .print-link.d-flex.justify-content-end
        %a{href: "javascript: print()"}
          = inline_svg_tag "ico-print.svg"
          Print Page
      = render partial: "benchmark_document_navigation"

app/views/layouts/_flash.html.erb
<div class="row">
  <div class="col">
    <% if notice.present? %>
      <div class="alert alert-primary">
        <%= notice %>
      </div>
    <% end %>
    <% if alert.present? %>
      <div class="alert alert-warning">
        <%= alert %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-blue">
  <div class="container">
    <% if Rails.application.config.logo %>
      <%= link_to root_url do %>
        <%= image_tag(Rails.application.config.logo[:src], alt: Rails.application.config.logo[:alt]) %>
      <% end %>
    <% end %>
    <button class="navbar-toggler text-white" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-end" id="navbarTogglerDemo02">
      <ul class="navbar-nav py-3">
        <li class="nav-item mx-lg-2">
          <a class="nav-link text-white py-1" href="<%= root_url %>">
            HOME
          </a>
        </li>
        <li class="nav-item mx-lg-2">
          <a class="nav-link text-white py-1" href="<%= introduction_url %>">
            WHO BENCHMARKS
          </a>
        </li>
        <li class="nav-item mx-lg-2">
          <a class="nav-link text-white py-1" href="<%= reference_library_url %>">
            REFERENCE LIBRARY
          </a>
        </li>
        <% if current_user %>
          <li class="nav-item dropdown ml-lg-2">
            <a class="nav-link text-white py-1 dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
              <%= current_user.email %>
              <span><%= image_tag("down-caret.svg", alt: "Down Caret") %></span>
            </a>
            <div class="dropdown-menu dropdown-menu-lg-right" aria-labelledby="navbarDropdownMenuLink">
              <%= link_to "My Plans", plans_url, class: "dropdown-item" %>
              <div class="dropdown-divider"></div>
              <%= button_to "Log Out", destroy_user_session_url, method: :delete, class: "dropdown-item", form: { "data-turbo": "false" } %>
            </div>
          </li>
        <% else %>
          <li class="nav-item ml-lg-2">
            <a class="nav-link text-white py-1" href="<%= new_user_session_url %>">
              LOG IN
            </a>
          </li>
        <% end %>
      </ul>
    </div>

  </div>

</nav>

<% if current_user&.admin? && current_page?(controller: :plans, action: :index) %>
  <nav class="navbar navbar-expand-lg admin-navbar">
    <div class="container">
      <h2 class="navbar-brand mb-0 font-weight-bold">Benchmarks Admin</h2>
      <ul class="navbar-nav">
        <li class="nav-item mx-lg-2">
          <%= link_to "Users", avo.resources_users_url, class: "nav-link" %>
        </li>
      </ul>
    </div>
  </nav>
<% end %>

app/views/layouts/_landing_page_footer.html.erb
<footer class="pt-4">
  <div class="bg-dark-blue pt-4">
    <div class="row p-0 m-0">
      <div class="col ml-5">
        <div class="row">
          <div class="col">
            <%= content_tag :span, "About", class: "heading" %>
          </div>
        </div>
        <div class="row pt-4">
          <div class="col">
            <span>This tool is designed to accelerate the planning process for National Action Plans for Health Security within the International Health Regulations (IHR) Monitoring and Evaluation Framework.</span>
          </div>
        </div>
      </div>
      <div class="col">
        <div class="row">
          <div class="col">
            <%= content_tag :span, "For Reference", class: "heading" %>
          </div>
        </div>
        <div class="row pt-4">
          <div class="col">
            <ul class="list-unstyled p-0">
              <li><%= link_to "JEE 1.0", "https://www.who.int/ihr/publications/WHO_HSE_GCR_2016_2/en/", class: "text-white", target: "_blank" %></li>
              <li><%= link_to "JEE 2.0", "https://www.who.int/ihr/publications/WHO_HSE_GCR_2018_2/en/", class: "text-white", target: "_blank" %></li>
              <li><%= link_to "e-SPAR", "https://extranet.who.int/e-spar", class: "text-white", target: "_blank" %></li>
            </ul>
          </div>
        </div>
      </div>
      <div class="col">
        <div class="row">
          <div class="col">
            <%= content_tag :span, "Contact", class: "heading" %>
          </div>
        </div>
        <div class="row pt-4">
          <div class="col">
            <ul class="list-unstyled p-0">
              <li><%= mail_to "sla@resolvetosavelives.org", "Report an Error" %></li>
              <li><%= link_to "Privacy Policy", privacy_policy_path %></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="row pt-5">
      <div class="col text-center">
        <%= link_to image_tag(image_path("prevent-epidemics-logo.svg")), "https://preventepidemics.org", target: "_blank", class: "footer-logo" %>
        <!-- <%= link_to image_tag(image_path("rtsl-logo.svg")), "https://www.resolvetosavelives.org", target: "_blank", class: "footer-logo" %> -->
        <!-- <%= link_to image_tag(image_path("world-bank.svg")), "https://www.worldbank.org/", target: "_blank", class: "footer-logo"  %> -->
        <!-- <%= link_to image_tag(image_path("cdc.svg")), "https://www.cdc.gov", target: "_blank", class: "footer-logo" %> -->
        <%= content_tag :p, "© #{Date.today.year}. World Health Organization. All rights reserved.", class: "py-3 copyright" %>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_standard_footer.html.erb
<footer class="bg-navy py-4">
  <div class="container mx-auto py-4">
    <span>
      <%= link_to "Privacy Policy", privacy_policy_path, target: "_blank" %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= mail_to Rails.application.config.contact_email, "Contact" %>
    </span>
    <% if Rails.application.config.copyright %>
      <span>
        <%= content_tag :p, Rails.application.config.copyright.call, class: "py-2 mb-0 copyright text-center" %>
      </span>
    <% end %>
  </div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title><%= Rails.application.config.site_title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"><%#= this meta tag is per Bootstrap: https://getbootstrap.com/docs/4.4/getting-started/introduction/  %>
    <%# NB: please refer to the section in README.md ## A note on js packs and stylesheets %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag which_js, "data-turbo-track": "reload", defer: true %>
    <%= javascript_include_tag("sentry", "data-turbo-track": "reload", defer: true) if Rails.env.production? %>
  </head>

  <body>
    <%= render "layouts/header" %>

    <% if content_for?(:homepage) %>
      <%= content_for :homepage %>
    <% else %>
      <div class="container page-container">

        <%= render partial: "layouts/flash" %>

        <div class="row">
          <div class="col-12">
            <div>
              <%= yield %>
            </div>
          </div>
        </div>
      </div>
    <% end %>

    <%= render "layouts/standard_footer" %>

  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title><%= Rails.application.config.site_title %></title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"><%#= this meta tag is per Bootstrap: https://getbootstrap.com/docs/4.4/getting-started/introduction/  %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  <%= javascript_include_tag("sentry", "data-turbo-track": "reload", defer: true) if Rails.env.production? %>
</head>

<body class="<%= controller_name == "registrations" ? "bg-dark-blue" : "bg-blue" %>">
  <div class="container h-100">
    <div class="row h-100">
      <div class="devise col-auto m-auto">

        <%= render partial: "layouts/flash" %>

        <div class="row">
          <div class="col m-4">
            <% if Rails.application.config.logo %>
              <%= image_tag(Rails.application.config.logo[:src], alt: "") %>
            <% end %>
          </div>
        </div>

        <div class="row no-gutters">
          <div class="col card rounded-10">
            <div class="col card-body">
              <%= yield %>
            </div>
          </div>
        </div>

        <%= yield :below_card %>
      </div>
    </div>
  </div>

</body>
</html>